name: Makefile CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # run manually

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Prepare
      run: make prepare 

    - name: Build
      run: make build

    - name: Start
      run: make start
